[env]
MODE = "debug"
EXAMPLE = "light_led"

[tasks.build_example_debug]
condition = { env = { "MODE" = "debug" } }
command = "cargo"
args = ["build", "--example", "${EXAMPLE}"]

[tasks.build_example_release]
condition = { env = { "MODE" = "release" } }
command = "cargo"
args = ["build", "--release", "--example", "${EXAMPLE}"]

#[tasks.objcopy_light_led]
#install_crate = "cargo-binutils"
#command = "cargo"
#args = ["objcopy", "--", "--strip-all", "-O", "binary", "target/riscv32imac-unknown-none-elf/debug/examples/light_led", "rom.bin"]

[tasks.objcopy]
command = ".tools/riscv-nuclei-elf-objcopy"
args = ["-O", "binary", "target/riscv32imac-unknown-none-elf/${MODE}/examples/${EXAMPLE}", "rom.bin"]
dependencies = [
  "build_example_debug",
  "build_example_release"
]

[tasks.flash]
command = ".tools/dfu-util"
args = ["-a", "0", "-s", "0x08000000:leave", "-D", "rom.bin"]
dependencies = [
  "objcopy"
]

[tasks.ocdflash]
command = ".tools/openocd"
args = ["-f", "./sipeed-jtag.cfg", "-f", "./openocd.cfg", "-c", "flash protect 0 0 last off; program {target/riscv32imac-unknown-none-elf/${MODE}/examples/${EXAMPLE}} verify; mww 0xe004200c 0x4b5a6978; mww 0xe0042008 0x01; resume; exit 0;"]
dependencies = [
	"build_example_debug",
	"build_example_release"
]

[tasks.example]
dependencies = [
    "ocdflash"
]
